import os
import sqlite3
from dotenv import load_dotenv
from langchain_community.utilities import SQLDatabase
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate

print("="*60)
print("🚀 CLASS 13: FULL-LOOP TEXT-TO-SQL FINANCIAL RAG AGENT")
print("="*60)

# Automatic load keys from the .env file
load_dotenv()

# Verify API Key
if not os.environ.get("GOOGLE_API_KEY"):
    print("❌ Error: .env file se GOOGLE_API_KEY nahi mila!")
    exit()

# Paths Setup
BASE_DIR = r"C:\Users\riaze\Desktop\TechCorp-Financial-RAG"
DB_PATH = os.path.join(BASE_DIR, "data", "csv", "financial_enterprise.db")

if not os.path.exists(DB_PATH):
    print(f"❌ Error: Database file nahi mili! Path: {DB_PATH}")
    exit()

# 1. Connect to Database for Schema Extraction
db = SQLDatabase.from_uri(f"sqlite:///{DB_PATH}")
table_schema_info = db.get_table_info()
print("✅ Database Schema loaded successfully.")

# 2. Initialize Google Gemini 2.5 Flash
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

# ============================================================
# STEP A: THE SQL GENERATION LAYER
# ============================================================
sql_prompt_template = """You are an expert SQL Developer. Given an input question, create a syntactically correct SQLite SELECT query to run.
Never execute any INSERT, UPDATE, or DELETE queries.
Return ONLY the raw SQL query inside your response. Do not include markdown blocks like ```sql or any extra text.

Database Schema Info:
{table_info}

Question: {input}
"""

sql_prompt = PromptTemplate(input_variables=["input", "table_info"], template=sql_prompt_template)

# Define the user's natural language question
user_question = "What is the total profit generated by Nvidia in the dataset?"
print(f"\n🤖 User Question: '{user_question}'")

# Generate SQL Query via Gemini 2.5
formatted_sql_prompt = sql_prompt.format(input=user_question, table_info=table_schema_info)
response_sql = llm.invoke(formatted_sql_prompt)
generated_sql = response_sql.content.strip()

print(f"🧠 Generated SQL: {generated_sql}")

# ============================================================
# STEP B: THE DATABASE EXECUTION LAYER
# ============================================================
print("\n⚡ Executing query on 1 Million rows database...")
try:
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(generated_sql)
    db_result = cursor.fetchall()
    conn.close()
    print(f"📊 Raw Database Result: {db_result}")
except Exception as e:
    print(f"❌ Database Execution Error: {e}")
    exit()

# ============================================================
# STEP C: THE FINANCIAL ANSWER SYNTHESIS LAYER
# ============================================================
print("\n📝 Synthesizing final human-friendly financial response...")

synthesis_prompt_template = """You are an expert Financial Analyst. 
Given a user's original question, the SQL query that was run, and the raw data result from the database, write a clear, professional, and easy-to-understand response for the company stakeholders.

Original Question: {question}
SQL Query Run: {query}
Raw DB Data: {result}

Provide a concise response summarizing the insight professionally.
"""

synthesis_prompt = PromptTemplate(
    input_variables=["question", "query", "result"],
    template=synthesis_prompt_template
)

formatted_synthesis_prompt = synthesis_prompt.format(
    question=user_question,
    query=generated_sql,
    result=str(db_result)
)

# Generate final narrative answer via Gemini 2.5
final_response = llm.invoke(formatted_synthesis_prompt)

print("\n" + "="*60)
print("🎯 FINAL RAG AGENT ANSWER FOR STAKEHOLDERS:")
print("-" * 60)
print(final_response.content.strip())
print("="*60)
print("\n✅ CLASS 13 SUCCESS: Full-Loop AI RAG Engine Execution Complete!")