import os
from dotenv import load_dotenv
from langchain_community.utilities import SQLDatabase
from langchain_google_genai import ChatGoogleGenerativeAI
# 🔥 LangChain ke naye versions ke liye updated import path:
from langchain.chains.sql_database.query import create_sql_query_chain
from langchain_core.prompts import PromptTemplate

print("="*60)
print("🚀 CLASS 12: LIVE TEXT-TO-SQL GEN-AI PROMPT CHAIN (.ENV MODE)")
print("="*60)

# Automatic load keys and paths from the .env file
load_dotenv()

# Verify if the key was loaded successfully from your .env
if not os.environ.get("GOOGLE_API_KEY"):
    print("❌ Error: .env file se GOOGLE_API_KEY nahi parh paya system!")
    print("💡 Tip: Check karein ke .env file isi main directory mein save hai.")
    exit()

# Paths Setup
BASE_DIR = r"C:\Users\riaze\Desktop\TechCorp-Financial-RAG"
DB_PATH = os.path.join(BASE_DIR, "data", "csv", "financial_enterprise.db")

if not os.path.exists(DB_PATH):
    print(f"❌ Error: Database file nahi mili dost! Path: {DB_PATH}")
    exit()

# 1. Connect to Database
db = SQLDatabase.from_uri(f"sqlite:///{DB_PATH}")
print("✅ LangChain connected to optimized SQLite Database.")

# 2. Initialize Google Gemini LLM:
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

# 3. Custom System Prompt Definition
custom_prompt_template = """You are an expert SQL Developer and Financial Data Analyst. 
Given an input question, create a syntactically correct SQLite query to run.
Never execute any INSERT, UPDATE, or DELETE queries. Only SELECT queries are allowed.

Here is the database schema information:
{table_info}

Question: {input}

Return ONLY the raw SQL query inside your response. Do not include markdown blocks like ```sql or any text. Just the executable SQL statement.
"""

prompt = PromptTemplate(
    input_variables=["input", "table_info"],
    template=custom_prompt_template
)

# 4. Create the Text-to-SQL Chain
sql_chain = create_sql_query_chain(llm, db, prompt=prompt)

# 🔥 --- LIVE TEST RUN WITH A NATURAL LANGUAGE QUESTION ---
user_question = "What is the total profit generated by Nvidia in the dataset?"
print(f"\n🤖 User Question: '{user_question}'")
print("🧠 Gemini is analyzing schema from environment variables and generating SQL...")

try:
    # Invoke the chain
    generated_sql = sql_chain.invoke({"question": user_question})
    
    print("\n" + "="*60)
    print("🎯 GEMINI GENERATED SQL QUERY:")
    print("-" * 60)
    print(generated_sql.strip())
    print("="*60)
    print("\n✅ CLASS 12 SUCCESS: AI Agent Is Safely Syncing via Environment Variables!")
except Exception as e:
    print(f"\n❌ Error during LLM Generation: {e}")